# Generated by Django 4.2.5 on 2023-11-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blackjack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="correct",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
