# Generated by Django 4.2.5 on 2023-11-30 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blackjack", "0002_hand_correct"),
    ]

    operations = [
        migrations.CreateModel(
            name="softTotal",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("not_ace", models.IntegerField()),
                ("dealer_up", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="pair",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("pair", models.IntegerField()),
                ("dealer_up", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="hardTotal",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("hard_total", models.IntegerField()),
                ("dealer_up", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
